flow log api
JioCloudVPC/ec2-api pull request #45
Opened 2016-10-04 20:23 UTC by abhilabh

Adding flow log for admin account

2016-10-08 05:57 UTC, hmdesai89 requested changes

2016-10-08 05:57 UTC, hmdesai89 commented on ec2api/api/__init__.py
> +			  'DescribeFlowLog' : ''
Please check indentation

2016-10-08 05:57 UTC, hmdesai89 commented on ec2api/api/cloud.py
> +                                    accountid=None,
Please create a parameter type for time. And check that in decorator instead of string. This will help to unify how user is entering time.

2016-10-08 05:57 UTC, hmdesai89 commented on ec2api/api/flow.py
> +    url = 'http://10.140.214.62:8081/analytics/query'
Do not hardcode the url. You can add it in config file, which is dynamically assigned. As this url will change for different environment.

2016-10-08 05:57 UTC, hmdesai89 commented on ec2api/api/flow.py
> +        return True;
We can have encoded password in the config file instead of plain text

2016-10-08 05:57 UTC, hmdesai89 commented on ec2api/api/flow.py
> +	raise exception.PasswordMissing(reason='admin password must be required')
Have you defined this exception ?

2016-10-08 05:57 UTC, hmdesai89 commented on ec2api/api/flow.py
> +        if admin_password and account_id is None:
Need not to check for admin password again.

2016-10-08 05:57 UTC, hmdesai89 commented on ec2api/api/flow.py
> +            data = '{"end_time": "%s" , "select_fields": ["vrouter", "sourcevn", "sourceip", "destvn", "destip", "protocol", "sport", "dport",  "direction_ing", "setup_time", "teardown_time","agg-pac
Is this part tested ? I see indentation error.

2016-10-08 05:57 UTC, hmdesai89 commented on ec2api/api/flow.py
> +            data = '{"end_time": "%s" , "select_fields": ["vrouter", "sourcevn", "sourceip", "destvn", "destip", "protocol", "sport", "dport",  "direction_ing", "setup_time", "teardown_time","agg-pac
Clean up code a bit. Here a portion of string variable 'data' remains constant. Append query string to that variable as needed.

2016-10-08 05:57 UTC, hmdesai89 commented on ec2api/api/flow.py
> +        raise exception.ConnectionError(reason=err)
Where is this exception defined.

2016-10-08 05:57 UTC, hmdesai89 commented on ec2api/api/flow.py
> +import ijson
Note the version of extra python packages that you will be using. This needs to be included in control file for packaging

2016-10-08 05:57 UTC, hmdesai89 commented on ec2api/api/flow.py
> +
Can you please add test case for this logic. Also we can have a call for the same.

2016-10-08 05:57 UTC, hmdesai89 commented on ec2api/api/flow.py
> +
Can you share data for time profiling in json.load and create_dict function. Also as discussed earlier share data for memory profiling as well.
Also split complete request in time chunks.
Keep a check on maximum time that we support

2016-10-08 05:57 UTC, hmdesai89 commented on ec2api/api/flow.py
> +
whats the maximum value of delta that we can support

2016-10-08 05:57 UTC, hmdesai89 commented on ec2api/api/flow.py
> +        return True;
Again, we should not save plain text password in conf file

2016-10-08 05:57 UTC, hmdesai89 commented on ec2api/api/flow.py
> +        if admin_password and account_id is None:
Please, take care of previous comments as well. We need not check admin_password again

2016-10-08 05:57 UTC, hmdesai89 commented on ec2api/api/flow.py
> +	raise exception.PasswordMissing(reason='admin password must be required')
Definition of this exception ??

2016-10-08 05:57 UTC, hmdesai89 commented on ec2api/api/flow.py
> +    return json.load(f)
Definition of this exception ??

2016-10-08 07:30 UTC, abhilabh commented on ec2api/api/flow.py
> +    return json.load(f)
I have defined this exception but it is not showing.
Initially I missed to git add exception.py file in first commit

2016-10-08 07:31 UTC, abhilabh commented on ec2api/api/flow.py
> +        return True;
I have saved password in cfg file with base64 encode.

2016-10-08 07:35 UTC, abhilabh commented on ec2api/api/flow.py
> +
we will set log for maximum 15 days so maximum value we will get from user will be 60*60*12*15=1296000.
I will add 15 day condition in start_time and end_time param checking.

2016-10-08 07:35 UTC, abhilabh commented on ec2api/api/cloud.py
> +                                    accountid=None,
ok I will update this and inform you.

2016-10-08 09:05 UTC, abhilabh commented on ec2api/api/__init__.py
> +			  'DescribeFlowLog' : ''
Harsh if we open the __init__.py indentation problem is not showing.

2016-10-10 06:14 UTC, hmdesai89 approved these changes
Looks ok to me. With some minor modification.

2016-10-10 06:14 UTC, hmdesai89 commented on ec2api/api/flow.py
> +
Please make a note of the new libraries that are used. And add it in build folder

2016-10-10 06:14 UTC, hmdesai89 commented on ec2api/exception.py
> +class AuthFailure(EC2InvalidException):
Please Remove this exception if its not called by anyone

2016-10-10 09:26 UTC, gdpak approved these changes

2016-10-10 09:26 UTC, merged